# Generated by Django 5.2.1 on 2025-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_flight_latitude_flight_longitude_flight_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(default='FL000', max_length=20, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('heading', models.FloatField(default=0)),
                ('trail', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plane',
                'verbose_name_plural': 'Planes',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
